update: sex 01 nov 2024 19:17:38 -03

diff --git a/dot_bin/executable_code-extensions b/dot_bin/executable_code-extensions
--- a/dot_bin/executable_code-extensions
+++ b/dot_bin/executable_code-extensions
@@ -1,21 +1,12 @@
 #!/bin/bash
 
-pkglist=(
-  ms-vscode.cpptools
-  donjayamanne.githistory
-  bradlc.vscode-tailwindcss
-  christian-kohler.path-intellisense
-  esbenp.prettier-vscode
-  miguelsolorio.min-theme
-  miguelsolorio.symbols
-  ms-python.python
-  ms-toolsai.jupyter
-  natqe.reload
-  nomicfoundation.hardhat-solidity
-  pomdtr.excalidraw-editor
-  prisma.prisma
-)
+LIST="$HOME/.config/Code/User/extensions.list"
 
-for i in ${pkglist[@]}; do
-  code --install-extension $i
+if [ ! -f "$LIST" ]; then
+  echo "File not found: $LIST"
+  exit 1
+fi
+
+for ext in $(cat "$LIST"); do
+  code --install-extension $ext --force
 done
